"""change allowed origin to allowed origins

Revision ID: 6d12ba94b08e
Revises: a53aafd61291
Create Date: 2026-06-03 12:17:42.909801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6d12ba94b08e'
down_revision: Union[str, Sequence[str], None] = 'a53aafd61291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_endpoints', sa.Column('allowed_origins', sa.Text(), nullable=True))
    op.drop_column('form_endpoints', 'allowed_origin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_endpoints', sa.Column('allowed_origin', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('form_endpoints', 'allowed_origins')
    # ### end Alembic commands ###