"""add form endpoint tables

Revision ID: a53aafd61291
Revises: f62045a39b3b
Create Date: 2026-06-03 10:59:02.854205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'a53aafd61291'
down_revision: Union[str, Sequence[str], None] = 'f62045a39b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('success_redirect_url', sa.Text(), nullable=True),
    sa.Column('error_redirect_url', sa.Text(), nullable=True),
    sa.Column('allowed_origin', sa.String(length=500), nullable=True),
    sa.Column('reply_to_field', sa.String(length=150), nullable=True),
    sa.Column('email_subject', sa.String(length=255), nullable=False),
    sa.Column('email_template', sa.Text(), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('smtp_security', sa.String(length=50), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('cap_enabled', sa.Boolean(), nullable=False),
    sa.Column('cap_verify_url', sa.Text(), nullable=True),
    sa.Column('cap_site_key', sa.String(length=255), nullable=True),
    sa.Column('cap_secret_key', sa.Text(), nullable=True),
    sa.Column('max_payload_kb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_endpoints_id'), 'form_endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_form_endpoints_slug'), 'form_endpoints', ['slug'], unique=True)
    op.create_table('form_endpoint_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['form_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_endpoint_recipients_endpoint_id'), 'form_endpoint_recipients', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_form_endpoint_recipients_id'), 'form_endpoint_recipients', ['id'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('origin', sa.String(length=500), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('reply_to_email', sa.String(length=255), nullable=True),
    sa.Column('cap_verified', sa.Boolean(), nullable=False),
    sa.Column('was_accepted', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['form_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_endpoint_id'), 'form_submissions', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_id'), 'form_submissions', ['id'], unique=False)
    op.create_table('email_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['form_endpoints.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_delivery_logs_endpoint_id'), 'email_delivery_logs', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_email_delivery_logs_id'), 'email_delivery_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_delivery_logs_submission_id'), 'email_delivery_logs', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_delivery_logs_submission_id'), table_name='email_delivery_logs')
    op.drop_index(op.f('ix_email_delivery_logs_id'), table_name='email_delivery_logs')
    op.drop_index(op.f('ix_email_delivery_logs_endpoint_id'), table_name='email_delivery_logs')
    op.drop_table('email_delivery_logs')
    op.drop_index(op.f('ix_form_submissions_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_endpoint_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_form_endpoint_recipients_id'), table_name='form_endpoint_recipients')
    op.drop_index(op.f('ix_form_endpoint_recipients_endpoint_id'), table_name='form_endpoint_recipients')
    op.drop_table('form_endpoint_recipients')
    op.drop_index(op.f('ix_form_endpoints_slug'), table_name='form_endpoints')
    op.drop_index(op.f('ix_form_endpoints_id'), table_name='form_endpoints')
    op.drop_table('form_endpoints')
    # ### end Alembic commands ###