"""replace submission storage with delivery metadata logs

Revision ID: e5a669540334
Revises: 6d12ba94b08e
Create Date: 2026-06-03 12:21:47.323587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = 'e5a669540334'
down_revision: Union[str, Sequence[str], None] = '6d12ba94b08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('cap_verified', sa.Boolean(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_summary', sa.Text(), nullable=True),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['form_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_delivery_logs_endpoint_id'), 'endpoint_delivery_logs', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_endpoint_delivery_logs_id'), 'endpoint_delivery_logs', ['id'], unique=False)
    op.drop_index('ix_email_delivery_logs_endpoint_id', table_name='email_delivery_logs')
    op.drop_index('ix_email_delivery_logs_id', table_name='email_delivery_logs')
    op.drop_index('ix_email_delivery_logs_submission_id', table_name='email_delivery_logs')
    op.drop_table('email_delivery_logs')
    op.drop_index('ix_form_submissions_endpoint_id', table_name='form_submissions')
    op.drop_index('ix_form_submissions_id', table_name='form_submissions')
    op.drop_table('form_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_submissions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('form_submissions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('payload_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reply_to_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cap_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('was_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['form_endpoints.id'], name='form_submissions_endpoint_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='form_submissions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_form_submissions_id', 'form_submissions', ['id'], unique=False)
    op.create_index('ix_form_submissions_endpoint_id', 'form_submissions', ['endpoint_id'], unique=False)
    op.create_table('email_delivery_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('smtp_host', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recipient_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['form_endpoints.id'], name='email_delivery_logs_endpoint_id_fkey'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], name='email_delivery_logs_submission_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='email_delivery_logs_pkey')
    )
    op.create_index('ix_email_delivery_logs_submission_id', 'email_delivery_logs', ['submission_id'], unique=False)
    op.create_index('ix_email_delivery_logs_id', 'email_delivery_logs', ['id'], unique=False)
    op.create_index('ix_email_delivery_logs_endpoint_id', 'email_delivery_logs', ['endpoint_id'], unique=False)
    op.drop_index(op.f('ix_endpoint_delivery_logs_id'), table_name='endpoint_delivery_logs')
    op.drop_index(op.f('ix_endpoint_delivery_logs_endpoint_id'), table_name='endpoint_delivery_logs')
    op.drop_table('endpoint_delivery_logs')
    # ### end Alembic commands ###